project:
  type: book
  output-dir: _docs

# https://prerelease.quarto.org/  # quarto documentation at this link

execute:
  eval: true
  echo: true
  output: true
  freeze: auto  # auto: during global project renders, re-render only when source changes

book:
  title: "Get IRS data for area targeting"
  subtitle: "Create csv file"
  # author: "Don Boyd"
  date: today
  date-format: long
  chapters:
    - index.qmd
    - part: "IRS Congressional District data"
      chapters:
        - cd_overall_documentation.qmd
        - cd_get_census_population.qmd
        - cd_download_soi_data.qmd
        - cd_construct_variable_documentation.qmd
        - cd_construct_data_file.qmd
        - cd_create_basefile_for_cd_target_files.qmd
        - cd_map_tcvars_and_extract_target_files.qmd
        
format:
  html:
    theme: cosmo
    code-fold: true    

editor_options:
  chunk_output_type: console

# R packages using old 209 libxml
#  gt, 


# rendering commands
#   quarto render
#   quarto publish netlify --no-prompt --no-render --no-browser

# possibly use this at start of each doc
# ---
# output: html_document
# editor_options: 
#   chunk_output_type: console
# ---

  
  