project:
  type: book
  output-dir: _docs

# https://prerelease.quarto.org/  # quarto documentation at this link

execute:
  eval: true
  echo: true
  output: true
  freeze: auto  # auto: during global project renders, re-render only when source changes

book:
  title: "Get IRS data for area targeting"
  subtitle: "Create csv file"
  # author: "Don Boyd"
  date: today
  date-format: long
  chapters:
    - index.qmd
    - part: "IRS Congressional District data"
      chapters:
        - overall_documentation_cd.qmd
        - download_data_cd.qmd
        - construct_variable_documentation.qmd
        - construct_cd_data_file.qmd
        # - map_cd_variables_to_puf_variables.qmd
        
format:
  html:
    theme: cosmo
    code-fold: true    

editor_options:
  chunk_output_type: console


# possibly use this at start of each doc
# ---
# output: html_document
# editor_options: 
#   chunk_output_type: console
# ---

  
  