project:
  type: book
  output-dir: _examine

# https://prerelease.quarto.org/  # quarto documentation at this link

execute:
  eval: true
  echo: true
  output: true
  freeze: auto  # auto: during global project renders, re-render only when source changes

book:
  title: "Examine area weights creation results"
  subtitle: "Create csv file"
  # author: "Don Boyd"
  date: today
  date-format: long
  chapters:
    - index.qmd
    - part: "IRS Congressional District data"
      chapters:
        # - cd_overall_documentation.qmd
        - cd_examine.qmd

        
format:
  html:
    theme: cosmo
    code-fold: true    

editor_options:
  chunk_output_type: console

# R packages using old 209 libxml
#  gt, 


# rendering commands
#   quarto render
#   quarto publish netlify --no-prompt --no-render --no-browser

# possibly use this at start of each doc
# ---
# output: html_document
# editor_options: 
#   chunk_output_type: console
# ---

  
  