project:
  type: book
  output-dir: _examine

# https://prerelease.quarto.org/  # quarto documentation at this link

# publishing with netllify cli:
#  open terminal in examine
# quarto render && netlify deploy --prod --dir=_examine

#  quarto render # inspect to be sure it is as desired
#  netlify deploy --prod --dir=_examine

# or step by step
#  netlify deploy # to test it, give _examine as publish directory
#  netlify deploy --prod   # to deploy, give _examine as publish directory

execute:
  eval: true
  echo: true
  output: true
  freeze: auto  # auto: during global project renders, re-render only when source changes

book:
  title: "Examine area weights creation results"
  subtitle: "Create csv file"
  # author: "Don Boyd"
  date: today
  date-format: long
  chapters:
    - index.qmd
    - part: "IRS Congressional District data"
      chapters:
        # - cd_overall_documentation.qmd
        - cd_prepare_data.qmd
        - cd_simple_tables.qmd
        - cd_results_vs_targets_tables.qmd

format:
  html:
    theme: cosmo
    code-fold: true    

editor_options:
  chunk_output_type: console

# R packages using old 209 libxml
#  gt, 


# rendering commands
#   quarto render
#   quarto publish netlify --no-prompt --no-render --no-browser

# possibly use this at start of each doc
# ---
# output: html_document
# editor_options: 
#   chunk_output_type: console
# ---

  
  