title: Tax microdata benchmarking
author: PSLmodels
copyright: 2024

execute:
  execute_notebooks: force

repository:
  url: https://github.com/pslmodels/tax-microdata-benchmarking
  branch: master
  path_to_book: docs

sphinx:
  config:
    html_js_files:
      - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.js
    html_theme: furo
    pygments_style: default
    html_css_files:
      - style.css
