name: Push

on:
  push:
    branches:
      - master

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v5
      - uses: psf/black@stable
        with:
          options: ". -l 79 --check"
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Build container
        run: docker build . -t ghcr.io/pslmodels/tax-microdata-benchmarking
      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build container
        run: docker build . -t ghcr.io/pslmodels/tax-microdata-benchmarking
      - name: Push container
        run: docker push ghcr.io/pslmodels/tax-microdata-benchmarking
